### ISSUE TITLE
Implement a managed API for bind, on, after and every

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#107]
It seems that those users who don’t want to dynamically control handlers seem to get confused for the requirement to retain handlers. Lets abstract this in the JavaScript scope. Implement a managed API for `bind`, `on`, `after` and `every`.

a.) Implement them to the global scope:

```javascript
bind('q', [ 'ctrl', 'shift' ], function () {});
on('screensDidChange', function () {});
after(double interval, function () {});
every(double interval, function () {});
```

b.) Create a prettier API with counter actions:

```javascript
Key.bind('q', [ 'ctrl', 'shift' ], function () {});
Key.unbind(handler);

Event.on('screensDidChange', function () {});
Event.off(handler);

Timer.after(1, function () {});
Timer.every(1, function () {});
Timer.stop(handler);
```

This will not change or break existing behaviour and advanced contexts can and should still manually manage handlers. We should also change all examples to use the managed API.

**Comment by mafredri** [comment]
I like a) for being concise and to the point, but also b) for being more clear. In favor of b), it might introduce new possibilities as well, e.g. `Key.availableKeys()` (could be used to bind all available keys temporarily) or what else could be dreamed up.

Also, since option a) doesn't have a way to unbind, we could return a callback function that unbinds, e.g.:

```js
var change = on('screensDidChange', function () {});
change(); // unbind
```

This pattern at least used to be pretty common in JS, not sure about where it stands today.

PS. Hyvää juhannusta! :)

**Comment by kasper** [comment]
@mafredri Kiitos, sitä samaa!

**Comment by kasper** [comment]
This has been now implemented and will be released in 2.1.2. I hope the new API is more consistent than the previous examples. This should also be a more familiar concept for new users. 😄 

```javascript
Key.on('q', [ 'ctrl', 'shift' ], function () {});
Key.off(identifier);

Event.on('screensDidChange', function () {});
Event.off(identifier);

Timer.after(1, function () {});
Timer.every(1, function () {});
Timer.off(identifier);
```

**Comment by mafredri** [comment]
Nice effort! :)

**Comment by kasper** [comment]
@mafredri Thanks! Obviously to get the full effect for keys, this also needs the KeyHandler change for binding (#99).
