### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by stevenhauser** [kasper/phoenix#122]
Hey, thanks for the awesome project! I couldn't find anywhere in the documentation whether Node 6 may be supported in the future. It appears that ES5 is supported now (unsure which node version is used for this project), while Node 6 supports almost all of ES2015 without Babel (which is a bit of a pain to use as a preprocessor in `.phoenix.js`). 

My question is whether adding support for Node 6 is on the roadmap, or better yet if there's a way to point to the node binary we want to use to run the JS, which would (theoretically) support all future versions of node. Thanks!

**Comment by kasper** [comment]
@stevenhauser Hello, thanks for the kind words! This project does not use Node.js as the JavaScript engine, instead we use JavaScriptCore from WebKit. This is the engine that Apple bundles in macOS. Currently, only JavaScript 5.1 is fully supported. When ES6 will be supported — it depends on when Apple pulls/updates the framework from the newer WebKit builds. Unfortunately, I have no idea when this will happen. Therefor Babel is still the easiest way to get the new features from ES6.

**Comment by stevenhauser** [comment]
Ohh ok that makes sense @kasper, thanks for answering! I know that Safari Technical Preview for the upcoming Safari 10 has claimed 100% ES2015 support so I wonder if that version of Webkit will be pulled into the next version of…Xcode or whatever when macOS ships in the fall. I've been really interested at looking to OSX's native JS automation APIs that they introduced a few months ago, too, but haven't gotten around to that. Hoping those will be ES2015 compatible with macOS too! Thanks again!

**Comment by kasper** [comment]
@stevenhauser Unfortunately there’s no mention of JavaScriptCore being updated in macOS Sierra, so it might take another major release. Who knows… Indeed Safari will support ES6.

The JavaScript automation API is very interesting, a good alternative to AppleScript. However, the API is a bit clunky at times.

**Comment by stevenhauser** [comment]
Gotcha, good to know @kasper!

**Comment by ngryman** [comment]
Haha, what a small world @stevenhauser 🎉 🎉🎉
I was going to propose the exact same thing, almost 3 years later 😛

@kasper As I was going to open a PR for this [one](https://github.com/kasper/phoenix/issues/51), I realized that Phoenix would really benefit from supporting ES6 (with modules) out of the box. It would definitely help people to write more complex stuff easily.

I think that a good solution would be to bundle and transpile the `phoenix.js` file before loading it. I could hack on something and open a PR if you are interested in.

**Comment by kasper** [comment]
@ngryman Currently, the supported version of JavaScript is based on the ECMAScript 6 standard. macOS versions prior to Sierra (10.12) support ECMAScript 5.1. Phoenix has no relation to Node, it uses the native JavaScript engine bundled in macOS (WebKit-based). All libraries have to be written in 5.1 to support older macOS versions. We already support preprocessing for older versions with for example Babel, but this cannot be used in the core.

**Comment by ngryman** [comment]
@kasper Thanks for the precisions! I understand that the runtime is JavaScriptCore and not Node. I was referring to preprocess the `phoenix.js` (the user provided config) before evaluating it. Here is my rationale, I may lack some context so please tell me if I'm missing something 😄

We could use Rollup to bundle and transpile the code at the same time so we get [ES6 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and code agnostic to the runtime environment.

I'm not a Objective-C specialist but I think this could be done like so:
- Patch the `loadScript` method [here](https://github.com/kasper/phoenix/blob/dcf80336d7d47d45b9505c9498f993ae9651e137/Phoenix/PHContext.m#L156)
- Invoke `rollup` in a subprocess and get `stdout` (the bundled and transpiled code).
- Pass it to `[self.context evaluateScript:script]`.

**Comment by kasper** [comment]
No bad intention taken, sorry if it sounded like that! To use Rollup you would create a dependency to have Node to run Phoenix which is not really desired since this is a standalone app. Modularised support would have to be implemented on the native level — there has been discussion about that though.

**Comment by ngryman** [comment]
@kasper Yes you're right, you'll need to have Node as a peer dependency.

Sorry if I push a little more, but would it be acceptable to detect that the user has Node installed and use Rollup if so, or fallback to the current behavior? I believe it's pretty likely that people interested in this will have Node already installed.

I'm insisting on this feature because I'm pretty confident that if you offer this out of the box, it will really help to build awesome stuff because now we could think about using `npm` packages for example 🎉

**Comment by kasper** [comment]
NPM packages would for the most part not work since the JavaScriptCore does not support Node APIs. It’s a separate virtual machine which only implements what is defined in Phoenix natively.

**Comment by mafredri** [comment]
@ngryman have you considered using webpack or something similar? It's what I use in my [phoenix-config](https://github.com/mafredri/phoenix-config) and it's been smooth sailing. When I'm hacking on Phoenix I just run `npm watch` (which just invokes `webpack --watch`) and then my bundled `phoenix.js` is updated whenever I make a change in my sources.

I think a better approach would be to create some type of `phoenix-starter` project which can set this up per default. Keeps Phoenix simple and JavaScript being JavaScript 😄.

**Comment by ngryman** [comment]
@mafredri Yup, I'm using Rollup on my side: https://github.com/ngryman/phoenix.

@kasper A good majority of `npm` packages are either agnostic or even target browsers rather than Node (ie. Lodash).

I still believe that offering a plug-and-play solution to users would be really valuable to the project as it would avoid to set up tooling for advanced configuration. I don't think it would come with a very high cost compared to the benefit it would bring. That said, I won't insist more, I can also understand your reasons about keeping Phoenix as standalone as possible.

I think that a `phoenix-starter` project would be a very good compromise indeed, it's a good suggestion 👍
