### ISSUE TITLE
Suggestion: Window#focus() without bringing to front

### ISSUE THREAD

**Issue by szhu** [kasper/phoenix#147]
If you ctrl-opt-click a window in macOS, it will become focused but not be brought to the front. Can Phoenix expose this functionality in `Window`?

My use case: I want to focus the window under the cursor. Code:

```coffee
Event.on 'mouseDidMove', ->
  mouseLocation = Mouse.location()
  for window in Window.recent()
    if isWithin(mouseLocation, window.frame())
      window.focusWithoutBringingToFront()  # <-- this is the requested feature
      break
```

PS Is there a function to get the window under the mouse?

**Comment by kasper** [comment]
Hello! I can certainly look into it. (You need to search the window under the mouse by looking through the coordinates manually.)

**Comment by kasper** [comment]
I’m not sure whether this is possible and I can’t find any reference to it in the APIs. In fact, Control + Option + Click seems to trigger a right click on the background window instead of just focusing it on macOS Sierra. (Try clicking on the titlebar of a Safari window that is in the background.) So maybe this is just a feature of “click-through”?

**Comment by szhu** [comment]
Okay yeah you're right. Thanks for looking into this.
