### ISSUE TITLE
Phoenix 2.4 doesn't show log messages at /var/log/system.log.

### ISSUE THREAD

**Issue by zehfernandes** [kasper/phoenix#162]
- Version: 2.4 (55)
- macOS: 10.12.2 (Sierra)

In the previous version (2.3) I monitor the file `/var/log/system.log` to receive status and variables from Phoenix.app. But after the update, this file stop logging this messages.

What file should I watch now? Because I still see the log messages at Mac console.
![screen shot 2017-01-12 at 02 19 00](https://cloud.githubusercontent.com/assets/1891339/21876823/871121c2-d86d-11e6-9fab-b20489c17a04.png)

**Comment by kasper** [comment]
I don’t think the update to the app caused this but rather upgrading to Sierra. Sierra has a new logging architecture called “Unified Logging” (https://developer.apple.com/library/content/releasenotes/MacOSX/WhatsNewInOSX/Articles/OSXv10.html).

According to the documentation: “Unified logging supersedes ASL (Apple System Logger) and the Syslog APIs. Messages are now stored in memory and a data store, rather than in text-based log files.”

That’s probably it, but I’ll have to verify this.

**Comment by kasper** [comment]
Yes, it seems they are not saved anymore to text-based log files.
