### ISSUE TITLE
Add option to ignore specific windows/apps

### ISSUE THREAD

**Issue by strflw** [kasper/phoenix#175]
First off: I just discovered Phoenix and I really like it. Thank you for this 💛

Currently there is only one thing I'm missing: The option to ignore specific windows by their App identifier.

For example, I'm using [Übersicht](https://github.com/felixhageloh/uebersicht) to create a statusbar-like widget on my Desktop.
That statusbar gets recognized as window by Phoenix.
Technically that's probably correct, but in practice the widget manages it's own size and behavior, thus it'd probably be a good thing to allow ignoring the windows of specific Apps by their `bundleIdentifier`.

Example:

    Phoenix.set({ ignoredApps: [ 'tracesOf.Uebersicht' ] })

Setting this will cause Phoenix to ignore all windows of the Übersicht App.

**Comment by kasper** [comment]
Hi! I’m glad you’re liking Phoenix! Any particular reason why you couldn’t do this with your own configuration? My idea is to keep the API as simple as possible.

**Comment by MaThGo** [comment]
So Phoenix rather aims to provide a Framework for Window Managing instead of actually being a Window Manager itself?

Because otherwise I'd say it should be part of Phoenix, because managing Windows (which IMHO includes ignoring) is the Job of a Window Manager.

There is no particular reason why I *__can't__* implement this in my configuration, just reasons why one might not _**want**_ it there.

If you don't see any value in implementing this, don't bother.

**Comment by kasper** [comment]
@MaThGo I can definitely see value in it. However, ignoring apps at the API level requires quite a bit of work instead of implementing the filtering in your configuration. So it’s a balance.
