### ISSUE TITLE
Custom Storage file path

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#188]
I need to generate a file using Phoenix that will be consumed by another program. 

How am I supposed to do that?

The Storage object would be perfect but I need the file to be written to a custom path.

I guess a workaround would be to run something like:
```
Task.run ( '/usr/local/bin/node', ['/path/to/logic.js', '--content', 'mycontent'] );
```

and then import the `fs` module in `logic.js`, but it seems unnecessarily convoluted for something so basic.

**Comment by mafredri** [comment]
I don't understand exactly what you're trying to accomplish, if I did i might be able to provide better suggestions. Anyway, I don't see why this couldn't be accomplished via shell instead of node:

```javascript
Task.run('/bin/sh' ['-c', `echo '${mycontent}' > /path/to/target.file`]);
```

In this example, it's important to consider shell quoting, e.g. since we're passing single-quotes (`'`) to `echo`, the content should not contain single quotes, or be properly escaped.

I believe kasper would say that writing files is out of scope for Phoenix, and I tend to agree. This logic should be pretty simple to abstract away behind a module/class/func if you need to construct such functionality :-).

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, that's exactly what I was looking for. I wasn't aware of the `-c` option 🙈.

I needed this for my [space switcher](https://github.com/fabiospampinato/phoenix) (bottom of the page).

I'm not going to close the issue though, I think having the ability to store everything inside Storage to a custom path is valuable.

There's actually a pretty nice way to provide support for this: by making `Storage.get ()` return the entire object. I believe it's a common practice in these kind of libraries to return everything in this case.

Having the entire storage, storing it somewhere is a matter of writing a function for that.

**Comment by kasper** [comment]
@mafredri :+1:

@fabiospampinato Any reason why it needs to be a custom path and you cannot just read the JSON-object from the default storage path?

**Comment by fabiospampinato** [comment]
@kasper I guess even the default storage path would do it, but what is it? I couldn't find a reference to that in the docs.

**Comment by kasper** [comment]
@fabiospampinato It’s `~/Library/Application Support/Phoenix/storage.json`.

**Comment by fabiospampinato** [comment]
Thanks, I just noticed that there's a paragraph about that in the readme, perhaps a line about it should also be added in the [Storage](https://github.com/kasper/phoenix/blob/2.5/docs/API.md#6-storage) section of the API documentation.

Thanks!

**Comment by kasper** [comment]
@fabiospampinato Yes, definitely should be added. Thanks for the feedback!
