### ISSUE TITLE
Switching spaces inside a shortcut handler is problematic

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#206]
- Version: 2.6.1 (65)
- macOS: 10.13.4 Beta

I have [this](https://github.com/fabiospampinato/phoenix/blob/master/helpers/switch_space.js/#L24-L26) bit of code inside a function, called by `Key.on ( ... )`, that triggers a space switch.

I'm not sure how it happens, but after a few times I execute the shortcut that triggers this function, `Key.on` starts to call it like crazy, like if I was keeping the shortcut keys pressed.

I can't reproduce it if I change the applescript in that piece of code to something else, like:

```javascript
const script = `display notification "Lorem ipsum dolor sit amet" with title "Title"`;
```

I can still reproduce it if I wrap `osascript ( script )` into `setTimeout ( () => ..., 0 )`, but I can't reproduce it if I set a delay of 100ms or something like that, so I guess there's some kind of race condition involved, possibly related to switching spaces.

**Comment by mafredri** [comment]
Could the problem be that you're still holding down a keyboard combination (e.g. what you used to activate that) and the via osascript issuing additional keycodes (whilst other modifiers are pressed on the physical keyboard).

That being said, I've occasionally noticed that a key event gets "stuck" in Phoenix, for example, I use `§` without modifiers as a hotkey for my terminal (show/hide). Sometimes when I've pressed it it has gotten stuck and the terminal keeps flickering. Pressing it again releases it.

I think this has happened when the system has otherwise been under heavy load or when Phoenix has just started. Maybe the release even can become lost under certain circumstances.

**Comment by fabiospampinato** [comment]
> Could the problem be that you're still holding down a keyboard combination (e.g. what you used to activate that) and then (via osascript) issuing additional keycodes (whilst other modifiers are pressed on the physical keyboard).

Maybe this is part of the problem, but I can't seem to be able to reproduce the issue more often by keeping the keys intentionally pressed.
