### ISSUE TITLE
Is it possible to implement 'hints' for window selection?

### ISSUE THREAD

**Issue by srustamo** [kasper/phoenix#25]
Is it possible to implement 'hints' for window selection?

**Comment by kasper** [comment]
Could you explain what you mean by “hints”? Thanks!

**Comment by srustamo** [comment]
A mode, which would show letter hints on screen for each window, pressing such letter would activate the relevant window. Perhaps this screenshot may be helpful. http://snag.gy/hKo6t.jpg

**Comment by kasper** [comment]
Okay, I see. So, do you have a set of keys that are mapped to the currently active windows (which of course change)? As it stands, Phoenix has a very light visual footprint and is targeted to run as hidden as possible. However, I understand your need. I’ll put this under consideration!

**Comment by kasper** [comment]
I’ve been thinking about this. Since keys bind callback functions, we really do not have any logical way to know exactly what that function will do. Only the *caller* can know that. Nor does it really make sense to bind windows as such to keys since they can change — sure, you can bind apps directly to keys.

Having said that, the upcoming version 2.0 has a generic idea of “modals” that can present a modal window with a message anywhere on the screen. You could use these yourself to implement hints. Currently they only support text, but it might be possible to add the ability to display the app icon as well.

**Comment by kasper** [comment]
@srustamo Just wanted to let you know, if you are still interested in trying Phoenix out, the next release will have the ability to use modals as visual hints (#126). 👍

**Comment by srustamo** [comment]
Thanks for the heads up.

On Aug 4, 2016, at 9:14 PM, Kasper Hirvikoski <notifications@github.com>
wrote:

@srustamo <https://github.com/srustamo> Just wanted to let you know, if you
are still interested in trying Phoenix out, the next release will have the
ability to use modals as visual hints (#126
<https://github.com/kasper/phoenix/issues/126>). 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kasper/phoenix/issues/25#issuecomment-237603469>, or mute
the thread
