### ISSUE TITLE
isMinimized and unMinimize incorrect

### ISSUE THREAD

**Issue by lukesmurray** [kasper/phoenix#269]
- Version: Version 2.6.6 (95)
- macOS: 10.15.7 

Reproduced with `slack`, `zoom`, `roam research`, `vscode`. 

To reproduce minimize an app then use a keyboard shortcut to query whether the app `isMinimized` and try to `unminimize` it.

**Comment by lukesmurray** [comment]
If it's applicable I used `app.mainWindow()`

**Comment by kasper** [comment]
Thanks! Just to confirm understanding, what was the actual result and expected behaviour?

**Comment by lukesmurray** [comment]
The isMinimize function returns false when a window is minimized. Unminimize returns false indicating it failed to succeed when a window is minimized. After minimizing a window I expect isMinimize to return true and unminimize to succeed.

**Comment by lukesmurray** [comment]
If isMinimize is working on your machine it's possible this has to do with customizations I've done to my dock in which case I'll need to investigate a bit more.

**Comment by lukesmurray** [comment]
Also thank you for this library. I know I've reported a couple of bugs but overall this is absolutely fantastic and a joy to work with. 🚀

**Comment by kasper** [comment]
@lukesmurray Thanks for the details, I’ll look into this when I have time. These just make it even better. Thanks for the kind words!

**Comment by kasper** [comment]
@lukesmurray Hey, thanks for reporting this! This was partly expected behaviour and a bug at the same time. Long story short, a minimised app will not have a main window and this is why you experienced this behaviour. The `App#mainWindow()` now correctly returns undefined in such cases.

You should use `App#windows()` instead if you want to have this toggling behaviour, since it will always contain even minimised windows. Hope this helps!
