### ISSUE TITLE
key binding works weird in 2.0

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#29]
my test config:

```
var mash = ["alt"];
Phoenix.bind('0', mash, function() {
  var modal = new Modal();
  modal.message = 'F!';
  modal.duration = 2;
  modal.show();
});

```

when I press `option + 0`, it leave a `º` in my current mouse postion, then call the `modal.show()`.

**Comment by kasper** [comment]
I switched to using the new `+ addGlobalMonitorForEventsMatchingMask:handler:` for key events, because it made key bindings much more easier. By design, “Events are delivered asynchronously to your app and you can only observe the event; you cannot modify or otherwise prevent the event from being delivered to its original target application.” As a consequence, if you have focus on an input this might be an inconvenience, I’ll have to think about this...

**Comment by kasper** [comment]
Oh, well. I’ll have to revert that decision and go back to the Carbon-museum.

**Comment by kasper** [comment]
Great, Phoenix 2.0 can now (again) bind keys exclusively. Thanks for making me aware of this!
