### ISSUE TITLE
App.launch changes

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#30]
`App.launch` in 1.x will launch or focus app.

`App.launch` in 2.x will only launch, now I must use code like this:

```
function launchOrFocus(appName) {
  var app = _.find(App.runningApps(), function(x) { return x.name() == appName});
  if (app === undefined) {
    App.launch(appName);
  } else {
    app.focus();
  }
}
```

**Comment by kasper** [comment]
This is by design, someone might not want to focus the app on launch. However, `App.launch()` now returns the app, so you can just call `focus()` on the returned instance like this: `App.launch('Safari').focus()`. If the app is already launched, it will return that instance. No need to loop the running apps.

**Comment by alswl** [comment]
ok, it works.
