### ISSUE TITLE
Binding keys with identical keys but different modifiers fails

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#32]
in my configuration: https://github.com/alswl/.oOo./blob/master/.phoenix.js#L281

```
Phoenix.bind('h', mashShift, function()
```
what I expected is move current windows to previous screen, but in 2.0, it moves a little space left.

It works well in 1.0, but error in 2.0.

Thanks.

**Comment by jasonm23** [comment]
Does both next and previous fail?

**Comment by alswl** [comment]
yes

On Mon, Sep 14, 2015 at 12:24 PM, JasonM23 <notifications@github.com> wrote:

> Does both next and previous fail?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kasper/phoenix/issues/32#issuecomment-139958959>.
>



-- 
-----------------------------------------
alswl
Blog: http://log4d.com/
Mail: alswlx[a]gmailDOTcom
-----------------------------------------

**Comment by kasper** [comment]
@alswl For me, there’s no behavioural difference between 1.0 and 2.0 with your configuration. I tested this on a setup with a smaller main screen (1280, 800) and a larger secondary screen (2560, 1440). That being said, you script doesn’t work when moving a larger window to a smaller screen, since you do not change the window size.

Could you explain what you are trying to achieve with your code and what your setup is? Especially, here https://github.com/alswl/.oOo./blob/master/.phoenix.js#L71. What do you expect the position to be on the new screen? Centred in both directions?

**Comment by alswl** [comment]
https://github.com/alswl/.oOo./blob/master/.phoenix.js#L71 the function makes current window move to the next screen, with the proportion size and proportion position.

in 1.0, `mashShitt + 'h'` put current window to next screen, `mashCtrl + h` move current window 100px left. And with same script, `mashShift +h` move current window 100px left, `mashCtrl +h` did nothing.

**Comment by kasper** [comment]
@alswl But `moveToScreen()` doesn’t change the window size. It just alters the x and y-position. How can it have a proportional size?

**Comment by alswl** [comment]
oh, my fault, I set x/y, but not set width/height.

But this error did not effect this issue.

**Comment by kasper** [comment]
@alswl Ok, unfortunately then you need to be more specific since I couldn’t see any difference with the behaviour on my setup. There shouldn’t be any change affecting this.

What are your screen sizes, what is the original frame of the window, to what position you are trying to move it and what is the frame of the window after the change.

(Unfortunately, the Accessibility API is a bit buggy when moving windows especially when your window is snapped to the top or bottom edge of the screen. I’ve reported this to Apple.)

**Comment by kasper** [comment]
@alswl Actually, by looking at this diff https://github.com/alswl/.oOo./commit/567df87cea8ce9cd7179bcb7e2687ea4f6b3895e. On lines 70–71 you should have `visibleFrameInRectangle()` instead of `frameInRectangle()`.

**Comment by kasper** [comment]
@alswl Did you get it working by fixing your configuration?

**Comment by alswl** [comment]
I fixed 'frameInRectangle()`.
I tried many windows, all of these don't work with `mashCtrl`.

Some more information, `mashCtrl + j` / `mashCtrl +k` works, but `mashCtrl + h/l` do not works.

`mashCtrl + j/k` moves current windows's vertical position.

**Comment by alswl** [comment]
any progress?

**Comment by kasper** [comment]
@alswl I still haven’t had time to thoroughly debug this, but I’m still struggling to grasp the nature of the issue. You also have referred to different keys on different comments, `mashCtrl` and `mashShift`, so I’m a bit confused. Would you be able to reiterate the problem a bit more?

**Comment by alswl** [comment]
Ok, I explain it again.

* configuration: https://github.com/alswl/.oOo./blob/78c66fc3893abc73de95109a83d6aa7fb791ee9e/.phoenix.js
* What I want
    * mashCtrl + j/k/h/l -> move current window down/up/left/right about 100px.
    * mashShift + h/l -> move current window to previous/next screen
* What happened:
    * mashCtrl + k/h, works
    * *mashCtrl + h/l*, nothing happened
    * *mashShift + h/l*, move current window left/right about 100px.

**Comment by alswl** [comment]
in vim, the two symbol is

```
^H^H^H^H^H^L^L^L^L^L^L^L^H^L^H^L^H^L^H^L^H
```

**Comment by kasper** [comment]
@alswl Excellent, thank you for the great description! Now I understand the setup. This should help me debug the issue.

**Comment by alswl** [comment]
cc5dafc do not fix this issue.

**Comment by kasper** [comment]
@alswl Ok, I’m back. So if I understand correctly, is this issue actually that the events are not getting fired at all for these specific key combinations? (You could test this with a console log in the callbacks — for instance.)

**Comment by kasper** [comment]
Aha, now I see the issue! There is something wrong with keys getting attached to wrong callbacks. Let me see how to fix this. Thanks for reporting!

**Comment by kasper** [comment]
@alswl Well, I feel stupid. This was a hashing issue related to key handlers. Handlers with identical keys but different modifiers would be considered the same. :( I wonder why no one else has run into this. Anyway, I’m so sorry it took so long for me to understand what the issue was. This should now be fixed in build 8. Would you be able to test it out?

**Comment by alswl** [comment]
perfect, now I can control my two monitors.

**Comment by kasper** [comment]
Brilliant, thanks!
