### ISSUE TITLE
Support using the "fn" key as a modifier

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#320]
- Version: 2.6.8
- macOS: 12.5.1

Is it possible to use the "fn" key as a modifier key?

**Comment by mafredri** [comment]
You can use Karabiner-Elements for this, it uses lower level input capture / rewrite. I doubt it’s possible via the APIs Phoenix uses but I could be wrong.

**Comment by fabiospampinato** [comment]
Good suggestion, but I'm trying to see if I can find a single-key modifier that I can reasonably use instead, which would allow me to remap the key with "hidutil", without any third-party program.

**Comment by mafredri** [comment]
I see. I can say with some certainty that you will want a key that behaves like a modifier. I once implemented modifier emulation and it was not the best experience due to having to rely on timeouts/key repeats.

For reference my commit that removed emulation: https://github.com/mafredri/phoenix-config/commit/d94863f6380a59a9bb2cdab742e2a5dc7eafa3f7
