### ISSUE TITLE
Ensuring cmd+space can be intercepted

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#327]
- Version: 3.0.0
- macOS: 12.5.1

Cmd+space can't be intercepted apparently:

```js
  Key.on ( 'space', ['cmd'], () => {
    // This is never called
  });
```

**Comment by kasper** [comment]
@fabiospampinato Hey! This is registered by macOS for Spotlight. You cannot register key combinations globally that are already registered by macOS or some other app.

**Comment by kasper** [comment]
Intercepting and keyboard shortcuts are different. Phoenix uses the official macOS API for registering keyboard shortcuts. You can also “tap” into global event streams (for providing accessibility features) and add/override behaviours for key events, this is what Alfred and Karabiner do to remap commands if I’m not mistaken. Tapping to key events is not supported in Phoenix at the moment and it would require a different API since the behaviour is different.
