### ISSUE TITLE
Window events can be a bit noisy with zero-frame and off-screen windows

### ISSUE THREAD

**Issue by shayne** [kasper/phoenix#39]
I'm working on a layout that depends on the events: `windowDidOpen` and `windowDidClose`. Unfortunately, `windowDidClose` isn't working as expected. It appears as if `NSAccessibilityUIElementDestroyedNotification` is reporting erratically, pretty much at any time *except* when a window is actually closed.

To repro: simply add an event handler for `windowDidClose`, log the app name and frame then start clicking around different apps.

![image](https://cloud.githubusercontent.com/assets/79330/10699318/ae6bad90-796a-11e5-91ff-08c4ea66d80f.png)

**Comment by kasper** [comment]
Bummer. Thanks for reporting!

**Comment by shayne** [comment]
I extracted the `AX` bits into a standalone app for testing. I think a good approach to fixing this would be to suppress the notifications to JS unless it's a window we're interested in. It's possible that the other notifications are for off-screen or zero-frame windows used by developers for various reasons.

I renege on my previous statement that the event wasn't reporting for actual closes, it is.

**Comment by kasper** [comment]
@shayne Yes, indeed the event will fire for all windows, visible or not. You can certainly do the filtering yourself. However, you are right that maybe there should be a higher level notification for “actual” windows.

**Comment by kasper** [comment]
@shayne I’m hesitant about doing anything about this. Obviously, a closed window has a zero-frame, because it doesn’t exist anymore. This is as expected. A user might also intensionally place a window off-screen, so it’s rather hard to determine when this is intentional or not.

It is true that developers use windows also in unconventional ways. This may cause confusing events. In fact, it seems that some apps do not even support these window level notifications. I’m not sure what they are doing to prevent the Accessibility API from reporting them. Summing this all up, it would seem better to leave the filtering up to the user to determine in an appropriate level.
