### ISSUE TITLE
Self build support?

### ISSUE THREAD

**Issue by jasonm23** [kasper/phoenix#54]
We should amend the `README.md` or maybe add a `INSTALL.md` file with self build instructions for developers who are interested in contributing.

**Comment by jasonm23** [comment]
Something along the lines of:

To build Phoenix yourself, you'll need:

- XCode 7.1.x
- XCode command line tools
- CocoaPods

        gem install cocoapods

From the terminal, clone the repo

    git clone https://github.com/kasper/phoenix

Run `pod install` in the `./phoenix` folder.

    cd ./phoenix
    pod install

Then build

    xcodebuild clean build

Your newly compiled app bundle will be in `./build/Release/`

**Comment by kasper** [comment]
I’ve already amended the install instructions from source. A basic `xcodebuild clean build` will not work anymore, but you shouldn’t need either Ruby or CocoaPods to get the build to work, since the Pods-directory is under version control. (CocoaPods is only required when updating the Pods for instance). However you are right that maybe we should document it in any case.

**Comment by kasper** [comment]
Okay, I added some additional notes. Hopefully it will make things clear enough.
