### ISSUE TITLE
Support Knowledge for Fullscreen State

### ISSUE THREAD

**Issue by timothysoehnlin** [kasper/phoenix#80]
I'm currently running into the issue that my layout code can't detect if a window is fullscreen and so it attempts to resize a full screened window (and does something weird).

I was looking at the [docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/index.html#//apple_ref/occ/instm/NSWindow/toggleFullScreen) attempting to see if there was any way to know if a window is in full screen mode or not. 

So far all I can see is i that there are events that fire when a window is moved into/out of fullscreen mode.

**Comment by kasper** [comment]
There’s an undocumented accessibility attribute that can be used to access this information through the official API. I have actually already implemented this on the `add-spaces-support`-branch, but Spaces-support is still under testing since it basically uses only undocumented and private APIs. I’m confident enough to cherry-pick and add this feature in the next release.

**Comment by alswl** [comment]
When you release the javascript API doc, you can mark it as "OSX private API, maybe not works later".

**Comment by kasper** [comment]
@alswl True, though I still want to prevent any obvious crashes.

**Comment by kasper** [comment]
@timothysoehnlin This has now been implemented in #60, is currently in master and will be released in 2.1. See [Window](https://github.com/kasper/phoenix/blob/master/API.md#18-window) for `isFullScreen()` and `setFullScreen(boolean value)`.

**Comment by timothysoehnlin** [comment]
This is awesome.  Thanks!
